baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Ivan's TechCraft"
theme = 'PaperMod'

[params]
  profileMode.enabled = true
  profileMode.title = "Ivan's TechCraft"
  profileMode.subtitle = "Welcome to my digital space for code, projects, and ideas."
  profileMode.imageUrl = ""
  profileMode.imageWidth = 120
  profileMode.imageHeight = 120
  profileMode.imageTitle = "profile picture"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/"
  [[params.socialIcons]]
    name = "reddit"
    url = "https://www.reddit.com/user/"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 40
