baseURL = 'https://ivanjara90.github.io/IvanJaraDev/'
languageCode = 'en-us'
title = "IvanJaraDev"
theme = 'PaperMod'

[params]
  customCSS = ["css/custom.css"]
  profileMode.enabled = true
  profileMode.title = "IvanJaraDev"
  profileMode.subtitle = "Welcome to my digital space for code, projects, and ideas."
  profileMode.imageUrl = "images/profile.jpg"
  profileMode.imageWidth = 200
  profileMode.imageHeight = 200
  profileMode.imageTitle = "profile picture"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/IvanJara90"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ivan-jara-recruter/"
  [[params.socialIcons]]
    name = "reddit"
    url = "https://www.reddit.com/user/IvanJara/"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/IvanJarBaq"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]